# Generated by Django 3.0.4 on 2022-07-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_user'),
        ('core', '0009_comment'),
    ]

    operations = [
    ]
