# Generated by Django 4.0.5 on 2022-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220724_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headerimg',
            field=models.ImageField(default='timeline-1.jpg', upload_to='header_images'),
        ),
    ]
